sudo : required

language : generic

servies:
  - docker

before_install :
  - echo " start creating an image with dockerfile"
  - docker build -t travis_ex -f Dockerfile.dev .

script:
  - docker run -e CI=true travis_ex npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker_ex"
  env: "Dockerex-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-352706020341"
  bucket_path : "elasticbeanstalk-ap-northeast-2-352706020341"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_ACCESS_KEY